/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.test.quickmath.view;

import com.test.quickmath.Constants;
import javax.swing.*;

/**
 *
 * @author duyvu
 */
public class HomeJFrame extends javax.swing.JFrame {

    private JLabel titleLabel;
    private JButton challengeButton;

    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initComponents();
        setupUI();
    }

    private void setupUI() {
        // Set frame properties
        setTitle("QuickMath");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setBackground(Constants.BACKGROUND_COLOR);
        setLayout(null);
        setSize(Constants.FRAME_WIDTH, Constants.FRAME_HEIGHT);
        setLocationRelativeTo(null);

        // Title
        titleLabel = new JLabel("Quick Math");
        titleLabel.setFont(Constants.TITLE_FONT);
        titleLabel.setBounds(0, Constants.TITLE_Y_POSITION, Constants.FRAME_WIDTH, Constants.BUTTON_HEIGHT);
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        add(titleLabel);

        // Challenge Button
        challengeButton = new JButton("Thử thách");
        challengeButton.setBounds(Constants.HORIZONTAL_MARGIN, Constants.FIRST_BUTTON_Y, 
                                Constants.BUTTON_WIDTH, Constants.BUTTON_HEIGHT);
        challengeButton.setBackground(Constants.BUTTON_PINK);
        challengeButton.setFont(Constants.BUTTON_FONT);
        add(challengeButton);

        // Add action listener to challenge button
        challengeButton.addActionListener(e -> {
            SettingJFrame challengeFrame = new SettingJFrame();
            challengeFrame.setVisible(true);
            dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // This method is intentionally left empty as we're using setupUI()
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            new HomeJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
